[package]
description       = "rspack fs"
edition.workspace = true
license           = "MIT"
name              = "rspack_fs"
repository        = "https://github.com/web-infra-dev/rspack"
version.workspace = true

[dependencies]
async-trait  = { workspace = true }
dunce        = { version = "1.0.5" }
pnp          = { version = "0.9.0" }
rspack_error = { path = "../rspack_error", workspace = true }
rspack_paths = { path = "../rspack_paths", workspace = true }
tokio        = { workspace = true, features = ["rt", "macros", "sync"] }
tracing      = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { workspace = true, features = ["rt", "macros", "sync", "fs"] }

[dev-dependencies]
tokio = { workspace = true, features = ["time"] }
